language: c

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
      env:
        - COVERAGE=true
        - CONFARGS="--enable-gcov --with-llvm=/usr/bin/llvm-config"
    - os: osx

addons:
  apt:
    packages:
      - automake
      - flex
      - llvm-dev
      - check
      - lcov

before_install:
  - >-
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      HOMEBREW_NO_AUTO_UPDATE=1 brew install llvm check
      export PATH=$PATH:$(brew --prefix llvm)/bin
    fi
      
install:
  - llvm-config --version
  - llvm-config --components

script:
  - ./autogen.sh
  - mkdir build && cd build
  - ../configure --enable-vhpi $CONFARGS
  - if [ -n "$COVERAGE" ]; then make cov-reset; fi
  - make check

after_success:
  - git config user.name "Travis CI"
  - git config user.email "$COMMIT_AUTHOR_EMAIL"
  - >-
    if [ -n "$COVERAGE" -a "$TRAVIS_BRANCH" = "master" ]; then
      make cov-report
      git clone https://$GITHUB_TOKEN:x-oauth-basic@github.com/nickg/nickg.github.io.git
      cp -ra coverage nickg.github.io
      cd nickg.github.io
      git add --all
      git commit -a -m "Travis CI coverage report"
      git push origin master
    fi

notifications:
  email: true
