language: c

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
    - os: osx

addons:
  apt:
    packages:
      - automake
      - flex
      - llvm-dev
      - check
      - lcov
      - python3-pip
      - python3-setuptools

before_install:
  - >-
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      HOMEBREW_NO_AUTO_UPDATE=1 brew install llvm check
      export PATH=$PATH:$(brew --prefix llvm)/bin
    fi
  - python3 -mpip install --user cpp-coveralls
      
install:
  - llvm-config --version
  - llvm-config --components

script:
  - ./autogen.sh
  - >-
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      ./configure --enable-vhpi
    else
      ./configure --enable-vhpi --enable-gcov --with-llvm=/usr/bin/llvm-config
    fi
  - make check

after_success:
  - >-
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      coveralls --gcov-options '\-lp' --exclude thirdparty \
        --exclude build --exclude config.h --exclude src/lexer.c
    fi

notifications:
  email: true
